@import "tailwindcss";

:root { --ink:#10243e; --muted:#64748b; --line:#e2e8f0; --surface:#f8fafc; --brand:#0f4c81; --accent:#d99b25; }
* { box-sizing:border-box; }
html { scroll-behavior:smooth; }
body { margin:0; color:var(--ink); background:#fff; font-family:Arial, Helvetica, sans-serif; }
a { color:inherit; text-decoration:none; }
.container { width:min(1160px, calc(100% - 32px)); margin:auto; }
.site-header { position:sticky; top:0; z-index:20; background:rgba(255,255,255,.94); backdrop-filter:blur(12px); border-bottom:1px solid var(--line); }
.nav { height:72px; display:flex; align-items:center; justify-content:space-between; }
.brand { display:flex; align-items:center; gap:10px; }.brand-mark { width:42px;height:42px;display:grid;place-items:center;border-radius:12px;background:var(--ink);color:#fff }.brand small,.brand strong{display:block}.brand strong{font-size:18px}.brand small{font-size:11px;color:var(--muted);margin-top:2px}.nav nav{display:flex;gap:24px;font-weight:600;color:#475569}.nav nav a:hover{color:var(--brand)}
.hero { background:linear-gradient(135deg,#eef5fb,#fff); border-bottom:1px solid var(--line); }.hero-inner{padding:96px 0 90px}.eyebrow{font-size:12px;font-weight:800;letter-spacing:.13em;color:var(--brand)}.hero h1{max-width:800px;font-size:clamp(40px,6vw,72px);line-height:1.02;margin:14px 0 20px;letter-spacing:-.045em}.hero p{max-width:700px;font-size:19px;line-height:1.7;color:var(--muted);margin:0}.hero-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.button{display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:12px 18px;border-radius:10px;font-weight:700;border:1px solid var(--line)}.button.primary{background:var(--ink);color:#fff;border-color:var(--ink)}.button.secondary{background:#fff}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:-28px;position:relative}.stat{background:#fff;border:1px solid var(--line);border-radius:16px;padding:22px;box-shadow:0 8px 30px rgba(15,23,42,.06)}.stat svg{color:var(--brand)}.stat strong{display:block;font-size:30px;margin-top:10px}.stat span{color:var(--muted);font-size:14px}.section{padding:82px 0}.section-heading,.page-heading{display:flex;justify-content:space-between;gap:20px;align-items:end}.section h2,.page-heading h1{font-size:40px;letter-spacing:-.035em;margin:8px 0}.text-link{font-weight:700;color:var(--brand)}.feature-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:28px}.feature-card{padding:28px;border:1px solid var(--line);border-radius:18px;transition:.2s}.feature-card:hover,.faculty-card:hover{transform:translateY(-3px);box-shadow:0 12px 32px rgba(15,23,42,.08)}.feature-card svg{color:var(--brand)}.feature-card h3{margin:22px 0 8px}.feature-card p{color:var(--muted);line-height:1.6}
.page-space{padding:58px 0 90px}.page-heading{display:block;margin-bottom:30px}.page-heading h1{font-size:48px}.page-heading p{color:var(--muted);font-size:17px}.filters{display:grid;grid-template-columns:1.6fr 1fr 1fr auto;gap:10px;margin-bottom:28px}.filters input,.filters select{height:46px;border:1px solid var(--line);border-radius:10px;padding:0 13px;background:#fff;color:var(--ink);outline:none}.filters input:focus,.filters select:focus{border-color:var(--brand)}.faculty-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.faculty-card{display:flex;gap:16px;border:1px solid var(--line);border-radius:16px;padding:16px;background:#fff;transition:.2s}.avatar{width:76px;height:76px;flex:0 0 76px;border-radius:14px;overflow:hidden;background:#e8eef5;display:grid;place-items:center;font-size:25px;font-weight:800;color:var(--brand)}.avatar img,.profile-photo img{width:100%;height:100%;object-fit:cover}.faculty-info{min-width:0}.faculty-info h3{font-size:17px;margin:6px 0 4px}.faculty-info p{margin:0;color:var(--muted);font-size:13px}.faculty-info small{display:block;color:#64748b;margin-top:8px;line-height:1.4}.dept{font-size:11px;font-weight:800;letter-spacing:.08em;color:var(--brand)}.empty{padding:70px 20px;text-align:center;border:1px dashed var(--line);border-radius:18px}.empty p,.muted{color:var(--muted)}
.back{display:inline-flex;align-items:center;gap:6px;color:var(--brand);font-weight:700;margin-bottom:24px}.profile-hero{display:grid;grid-template-columns:170px 1fr;gap:28px;align-items:center;padding:28px;border:1px solid var(--line);border-radius:22px;background:linear-gradient(135deg,#f8fbff,#fff)}.profile-photo{width:170px;height:170px;border-radius:20px;overflow:hidden;background:#e8eef5;display:grid;place-items:center;font-size:50px;font-weight:800;color:var(--brand)}.profile-hero h1{font-size:42px;letter-spacing:-.035em;margin:8px 0}.role{font-size:18px;color:var(--muted);margin:0 0 18px}.contact-row{display:flex;gap:16px;flex-wrap:wrap;margin-top:9px}.contact-row a{display:inline-flex;gap:6px;align-items:center;color:var(--brand);font-size:14px}.profile-grid{display:grid;gap:18px;margin-top:22px}.content-card{border:1px solid var(--line);border-radius:18px;padding:25px}.content-card h2{display:flex;align-items:center;gap:9px;margin:0 0 18px;font-size:22px}.content-card h2 span{font-size:12px;background:#eef5fb;padding:4px 8px;border-radius:999px;color:var(--brand)}dl{margin:0}dt{font-size:12px;font-weight:800;color:var(--muted);margin-top:16px;text-transform:uppercase;letter-spacing:.06em}dd{margin:6px 0 0;line-height:1.6}.list article{padding:16px 0;border-top:1px solid var(--line)}.list article:first-child{border-top:0;padding-top:0}.list h3{font-size:16px;margin:0 0 6px}.list p,.list small{color:var(--muted);line-height:1.5}.list a,.links a{display:inline-flex;align-items:center;gap:5px;color:var(--brand);font-weight:700;font-size:13px;margin-top:7px}.chips{display:flex;flex-wrap:wrap;gap:8px;padding:0;margin:0;list-style:none}.chips li{border:1px solid var(--line);padding:8px 12px;border-radius:999px;background:var(--surface);font-size:14px}.links{display:flex;flex-wrap:wrap;gap:14px}.links a{border:1px solid var(--line);padding:10px 12px;border-radius:9px;margin:0}
footer{border-top:1px solid var(--line);background:var(--surface)}.footer-inner{padding:28px 0;display:flex;justify-content:space-between;gap:20px;color:var(--muted);font-size:13px}.footer-inner strong{color:var(--ink)}.footer-inner p{margin:5px 0}
@media(max-width:850px){.stats,.feature-grid,.faculty-grid{grid-template-columns:repeat(2,1fr)}.filters{grid-template-columns:1fr 1fr}.filters .button{grid-column:span 2}.profile-hero{grid-template-columns:110px 1fr}.profile-photo{width:110px;height:110px}.profile-hero h1{font-size:32px}}
@media(max-width:560px){.container{width:min(100% - 22px,1160px)}.nav nav{gap:12px}.hero-inner{padding:64px 0}.hero h1{font-size:42px}.stats,.feature-grid,.faculty-grid{grid-template-columns:1fr}.section-heading{display:block}.filters{grid-template-columns:1fr}.filters .button{grid-column:auto}.profile-hero{grid-template-columns:1fr}.profile-photo{width:120px;height:120px}.profile-hero h1{font-size:30px}.footer-inner{display:block}}
